### ISSUE TITLE
Separate text and values

### ISSUE THREAD

**Issue by GStilow** [Chessmasterrr/SimpleStatsWidget#1]
As for me, the widget box is higher than wide. Thus I would suggest to set the text "SMS" and "Calls" on top of the corresponding value. 
Then it should look like a chart, with all entries having the same orientation.

It might also be nice to change the background colour a bit, lets say the text gets a dark grey and the values stay with a black, to immediately see what you are looking for.

**Comment by Chessmasterrr** [comment]
It's a good idea to set the headers above the values to get a cleaner layout. The widget could then probably be quadratic and not with different sizes for height and width. I will implement it in the next release.

The colors are a different topic, maybe I will make them fully customizable - see #2.

**Comment by Chessmasterrr** [comment]
Fixed with f69682e
