### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sphh** [Chessmasterrr/SimpleStatsWidget#13]
Could you please make a new release, so that F-Droid can serve the new features?

Thanks.

**Comment by Chessmasterrr** [comment]
I was hoping that I find time to fix #12 before the next release, but it looks like it didn't work out in time. So here is the next release that will be served in a few days via F-Droid - I will leave this issue open until then.

**Comment by Chessmasterrr** [comment]
Something is broken in F-Droid, see https://gitlab.com/fdroid/fdroiddata/issues/1755

**Comment by sphh** [comment]
Thanks. Great. Looks like this is a common problem at F-Droid:https://gitlab.com/fdroid/fdroiddata/issues?scope=all&utf8=%E2%9C%93&state=opened&search=outdated%3A

I did not get any updates for any app for the last couple of days.

**Comment by licaon-kter** [comment]
@Chessmasterrr Any news?

**Comment by Chessmasterrr** [comment]
Next try with version 1.2.1. Hopefully it will build in F-Droid...

**Comment by Chessmasterrr** [comment]
The new version is now deployed via F-Droid.

**Comment by sphh** [comment]
Thank you so much!!
