### ISSUE TITLE
Show remaining call minutes/texts instead of used values

### ISSUE THREAD

**Issue by sphh** [Chessmasterrr/SimpleStatsWidget#9]
Would it be possible to show remaining texts and minutes instead of the texts and minutes already used?

**Comment by Chessmasterrr** [comment]
Sure, it should be possible to set the maximum values for calls and SMS at installation time of the widget and show then the remaining values.
I will add this feature when I find some time to do it.
What do you expect to happen when the maximum values are reached? Just display 0 for the rest of the month, or display the overused time with a minus, or something else?

**Comment by sphh** [comment]
Thanks for considering this.

I can think of two ways:

1. Display a minus sign in front of the overused time/text messages.
2. Colour the foreground or background red.

Honestly I don't know which is the better way. I would be happy with both options.

**Comment by Chessmasterrr** [comment]
Thanks for your thoughts!
I think just changing the color of the foreground or background can be confusing, especially for people with red/green weakness - but I like the idea of combining both approaches. I will try to implement this within this month.

**Comment by sphh** [comment]
I do like the idea of combining both approaches (and you are right about the red/green weakness!).

**Comment by Chessmasterrr** [comment]
Fixed in the master branch, will be added in the next release.
Please note in this context #12.
